FROM rust:slim-trixie AS febuilder
WORKDIR app
COPY . .
RUN echo $(ls -l /app)
RUN rustup target add wasm32-unknown-unknown
RUN cargo install wasm-bindgen-cli
RUN cargo install trunk
RUN cd /app/frontend/ && trunk build


FROM rust:slim-trixie AS runtime
WORKDIR app
COPY --from=febuilder /app/frontend/dist/ /app/
COPY --from=febuilder /app/serve.py /app/
RUN echo $(ls -1 /app)
EXPOSE 8000
CMD ["python3", "serve.py"]
